resources:
- name: every-1m
  type: time
  icon: clock-outline
  source:
    interval: 1m

jobs:
  - name: ansible-pipeline
    public: true
    plan:
      - get: every-1m
        trigger: true
      - task: ansible-pipeline
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: abhiram85/pocdeploy}
          run:
            path: /bin/sh
            args:
            - -exec
            - |
              sh /ansible/playbooks/run.sh
